// GENERATED FILE - DO NOT EDIT MANUALLY.
// Source: access-control/modules/*.yml
export const PERMISSION_CODES = {
  ACCESS_PERMISSION_READ: 'access.permission.read',
  ACCESS_ROLE_READ: 'access.role.read',
  ACCESS_ROLE_CREATE: 'access.role.create',
  ACCESS_ROLE_UPDATE: 'access.role.update',
  ACCESS_ROLE_CLONE: 'access.role.clone',
  ACCESS_ROLE_DEACTIVATE: 'access.role.deactivate',
  ACCESS_ROLE_PERMISSION_ASSIGN: 'access.role.permission.assign',
  ACCESS_USER_READ: 'access.user.read',
  ACCESS_USER_ROLE_ASSIGN: 'access.user.role.assign',
  ACCESS_USER_PERMISSION_OVERRIDE: 'access.user.permission.override',
  ACCESS_EFFECTIVE_PERMISSION_READ: 'access.effective-permission.read',
  ACCESS_AUDIT_READ: 'access.audit.read',
  CUSTOMER_READ: 'customer.read',
  CUSTOMER_CREATE: 'customer.create',
  CUSTOMER_UPDATE: 'customer.update',
  CUSTOMER_DEACTIVATE: 'customer.deactivate',
  CUSTOMER_ADDRESS_MANAGE: 'customer.address.manage',
  CUSTOMER_AUDIT_READ: 'customer.audit.read',
  EMPLOYEE_READ: 'employee.read',
  EMPLOYEE_READ_SELF: 'employee.read-self',
  EMPLOYEE_CREATE: 'employee.create',
  EMPLOYEE_UPDATE: 'employee.update',
  EMPLOYEE_STATUS_CHANGE: 'employee.status.change',
  EMPLOYEE_ACCOUNT_LINK: 'employee.account.link',
  EMPLOYEE_ACCOUNT_UNLINK: 'employee.account.unlink',
  EMPLOYEE_BRANCH_ASSIGN: 'employee.branch.assign',
  EMPLOYEE_BRANCH_REMOVE: 'employee.branch.remove',
  EMPLOYEE_POSITION_ASSIGN: 'employee.position.assign',
  EMPLOYEE_POSITION_READ: 'employee.position.read',
  EMPLOYEE_POSITION_MANAGE: 'employee.position.manage',
  EMPLOYEE_AUDIT_READ: 'employee.audit.read',
  EMPLOYEE_MANAGE_ALL_BRANCHES: 'employee.manage-all-branches',
  EMPLOYEE_COMPENSATION_READ: 'employee.compensation.read',
  EMPLOYEE_COMPENSATION_UPDATE: 'employee.compensation.update',
  EMPLOYEE_COMPENSATION_HISTORY_READ: 'employee.compensation.history.read',
  EMPLOYEE_IDENTITY_MASKED_READ: 'employee.identity.masked-read',
  EMPLOYEE_IDENTITY_READ: 'employee.identity.read',
  EMPLOYEE_IDENTITY_UPDATE: 'employee.identity.update',
  EMPLOYEE_FILE_READ: 'employee.file.read',
  EMPLOYEE_FILE_UPLOAD: 'employee.file.upload',
  EMPLOYEE_FILE_REPLACE: 'employee.file.replace',
  EMPLOYEE_FILE_DELETE: 'employee.file.delete',
  EMPLOYEE_FILE_DOWNLOAD: 'employee.file.download',
  ITEM_TYPE_READ: 'item-type.read',
  ITEM_TYPE_CREATE: 'item-type.create',
  ITEM_TYPE_UPDATE: 'item-type.update',
  ITEM_TYPE_ARCHIVE: 'item-type.archive',
  LOCATION_READ: 'location.read',
  NOTIFICATION_READ_OWN: 'notification.read-own',
  NOTIFICATION_MARK_READ_OWN: 'notification.mark-read-own',
  NOTIFICATION_MARK_ALL_READ_OWN: 'notification.mark-all-read-own',
  NOTIFICATION_DISMISS_OWN: 'notification.dismiss-own',
  NOTIFICATION_PREFERENCES_MANAGE_OWN: 'notification.preferences.manage-own',
  NOTIFICATION_SEND_SPECIFIC: 'notification.send-specific',
  NOTIFICATION_SEND_EMPLOYEE: 'notification.send-employee',
  NOTIFICATION_BROADCAST_BRANCH_USERS: 'notification.broadcast-branch-users',
  NOTIFICATION_BROADCAST_BRANCH_EMPLOYEES: 'notification.broadcast-branch-employees',
  NOTIFICATION_SEND_BY_POSITION: 'notification.send-by-position',
  NOTIFICATION_SEND_BY_PERMISSION: 'notification.send-by-permission',
  NOTIFICATION_MANAGE: 'notification.manage',
  PRICE_LIST_READ: 'price-list.read',
  PRICE_LIST_CREATE: 'price-list.create',
  PRICE_LIST_UPDATE_DRAFT: 'price-list.update-draft',
  PRICE_LIST_DUPLICATE: 'price-list.duplicate',
  PRICE_LIST_PUBLISH: 'price-list.publish',
  PRICE_LIST_ARCHIVE: 'price-list.archive',
  PRICE_RULE_READ: 'price-rule.read',
  PRICE_RULE_CREATE: 'price-rule.create',
  PRICE_RULE_UPDATE_DRAFT: 'price-rule.update-draft',
  PRICE_RULE_DELETE_DRAFT: 'price-rule.delete-draft',
  PRICE_RULE_OVERRIDE_CONFLICT: 'price-rule.override-conflict',
  PRICING_PREVIEW: 'pricing.preview',
  PRICING_READ_HISTORY: 'pricing.read-history',
  SERVICE_READ: 'service.read',
  SERVICE_CREATE: 'service.create',
  SERVICE_UPDATE: 'service.update',
  SERVICE_ARCHIVE: 'service.archive',
} as const

export type PermissionCode = typeof PERMISSION_CODES[keyof typeof PERMISSION_CODES]

export const ALL_PERMISSION_CODES: readonly PermissionCode[] = Object.values(PERMISSION_CODES)
