package com.laundry.management.common.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    CUSTOMER_NOT_FOUND,
    CUSTOMER_PHONE_DUPLICATE,
    CUSTOMER_VERSION_CONFLICT,
    CUSTOMER_ADDRESS_NOT_FOUND,
    CUSTOMER_ADDRESS_MISMATCH,
    CUSTOMER_ACTIVITY_NOT_FOUND,
    CUSTOMER_INACTIVE,
    INVALID_CUSTOMER_STATUS,
    INVALID_ADDRESS_STATUS,
    INVALID_DEFAULT_ADDRESS_REPLACEMENT,
    INVALID_SORT,
    PAGE_SIZE_EXCEEDED,
    BRANCH_ACCESS_DENIED,
    INTERNAL_ERROR
}
