import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, ArrowLeft, CheckCircle2, ChevronLeft, ChevronRight, CircleCheck, Clock3, Cog, FileText, Search, ShoppingBasket, XCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ApiError } from '../../api/client'
import { useAuth } from '../../auth/AuthProvider'
import { PERMISSION_CODES } from '../../auth/permissionCodes.generated'
import { ConfirmDialog, OverlayDialog } from '../../components/OverlayDialog'
import { ErrorState, LoadingState, StatePanel } from '../../components/States'
import { Field } from '../../components/Field'
import { Button, ButtonLink } from '../../components/ui/Button'
import { CollapsibleFilterPanel } from '../../components/ui/CollapsibleFilterPanel'
import { StatCard } from '../../components/ui/StatCard'
import { Surface } from '../../components/ui/Surface'
import { useRealtime } from '../../realtime/context'
import { useToast } from '../../providers/ToastProvider'
import { batchKeys, washBatchApi } from './api'
import { BatchCandidateCard, BatchItemGroups, BatchStatusChip } from './BatchComponents'
import { candidateCompatibility, quantitiesText, warningText } from './presentation'
import type { BatchHistory, BatchItem } from './types'

const when=(value:string)=>new Date(value).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})
const historyText:Record<string,string>={CREATED:'Tạo mẻ',ITEMS_ADDED:'Thêm đồ vào mẻ',ITEMS_REMOVED:'Xóa đồ khỏi mẻ',NOTE_UPDATED:'Cập nhật ghi chú mẻ',MARKED_READY:'Đánh dấu sẵn sàng',CANCELLED:'Hủy mẻ'}
const localDayBoundary=(value:string,offset:number)=>{const [year,month,day]=value.split('-').map(Number);return year&&month&&day?new Date(year,month-1,day+offset).toISOString():undefined}
function apiMessage(error:unknown){if(!(error instanceof ApiError))return 'Không thể hoàn tất thao tác.';return ({BATCH_VERSION_CONFLICT:'Mẻ giặt vừa được người khác cập nhật.',BATCH_ITEM_ALREADY_ASSIGNED:'Một món vừa được xếp vào mẻ khác.',BATCH_INCOMPATIBLE:'Không thể ghép các món đã chọn.',BATCH_IMMUTABLE:'Mẻ đã sẵn sàng nên không thể thay đổi thành phần.'} as Record<string,string>)[error.problem.errorCode??'']??error.message}

type MainTab='DRAFT'|'READY'|'PROCESSING'|'COMPLETED'|'CANCELLED'
const mainTabs = [
  ['DRAFT', 'Mẻ nháp', FileText],
  ['READY', 'Sẵn sàng', CheckCircle2],
  ['PROCESSING', 'Đang xử lý', Cog],
  ['COMPLETED', 'Hoàn tất', CircleCheck],
  ['CANCELLED', 'Đã hủy', XCircle],
] as const

export function WashBatchListPage(){
  const {branchId}=useAuth();const queryClient=useQueryClient();const {subscribe}=useRealtime()
  const [tab,setTab]=useState<MainTab>('DRAFT');const [search,setSearch]=useState('');const [page,setPage]=useState(0)
  const [serviceId,setServiceId]=useState('');const [createdBy,setCreatedBy]=useState('');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [loadType,setLoadType]=useState('');const [warning,setWarning]=useState('')
  const stats=useQuery({queryKey:batchKeys.stats(branchId),queryFn:()=>washBatchApi.stats(branchId!),enabled:Boolean(branchId)})
  const filterOptions=useQuery({queryKey:batchKeys.filterOptions(branchId),queryFn:()=>washBatchApi.filterOptions(branchId!),enabled:Boolean(branchId)})
  const batches=useQuery({queryKey:batchKeys.list(branchId,tab,search,page,serviceId?Number(serviceId):undefined,createdBy?Number(createdBy):undefined,from,to,loadType,warning),queryFn:()=>washBatchApi.list({branchId:branchId!,status:tab,search:search||undefined,page,size:20,serviceId:serviceId?Number(serviceId):undefined,createdBy:createdBy?Number(createdBy):undefined,createdFrom:from?localDayBoundary(from,0):undefined,createdTo:to?localDayBoundary(to,1):undefined,loadType:loadType||undefined,warning:warning||undefined}),enabled:Boolean(branchId)})
  const tabCount=(value:MainTab)=>{if(tab===value)return batches.data?.totalElements;if(value==='DRAFT')return stats.data?.draftCount;if(value==='READY')return stats.data?.readyCount;return undefined}
  const activeFilterCount=[serviceId,createdBy,from,to,loadType,warning].filter(Boolean).length
  const clearFilters=()=>{setServiceId('');setCreatedBy('');setFrom('');setTo('');setLoadType('');setWarning('');setPage(0)}
  useEffect(()=>subscribe('batch.',()=>{void queryClient.invalidateQueries({queryKey:batchKeys.all})}),[queryClient,subscribe])
  return <div className="page-container wash-batch-page"><header className="page-header batch-page-hero"><div><p className="page-kicker">Điều phối xử lý</p><h1>Mẻ giặt</h1><p>Theo dõi và quản lý các mẻ đã được ghép từ trang Đơn hàng.</p></div></header>
    <div className="batch-stats" aria-label="Tổng quan mẻ giặt"><StatCard icon={<ShoppingBasket/>} label="Đồ chờ ghép" value={stats.data?.candidateCount??'—'} tone="operational"/><StatCard icon={<FileText/>} label="Mẻ nháp" value={stats.data?.draftCount??'—'} tone="primary"/><StatCard icon={<CheckCircle2/>} label="Mẻ sẵn sàng" value={stats.data?.readyCount??'—'} tone="success"/></div>
    <div className="batch-tabs" role="tablist" aria-label="Trạng thái mẻ">{mainTabs.map(([value,label,Icon])=>{const count=tabCount(value);return <button id={`batch-tab-${value.toLowerCase()}`} data-status={value.toLowerCase()} key={value} type="button" role="tab" aria-controls="batch-panel" aria-selected={tab===value} onClick={()=>{setTab(value);setPage(0)}}><span className="batch-tabs__icon"><Icon size={18} aria-hidden="true"/></span><span>{label}</span><span className={`batch-tabs__count${count===undefined?' batch-tabs__count--placeholder':''}`} aria-hidden="true">{count??0}</span></button>})}</div>
    <Surface id="batch-panel" className="batch-board" role="tabpanel" aria-labelledby={`batch-tab-${tab.toLowerCase()}`}><div className="batch-toolbar"><label className="batch-search"><Search size={19} aria-hidden="true"/><span className="sr-only">Tìm kiếm</span><input value={search} onChange={event=>{setSearch(event.target.value);setPage(0)}} placeholder="Tìm theo mã mẻ"/></label><span className="batch-count" aria-live="polite">{batches.isLoading?'Đang tải':`${batches.data?.totalElements??0} mẻ`}</span></div>
      <CollapsibleFilterPanel className="batch-advanced-filters" label="Bộ lọc nâng cao" activeCount={activeFilterCount} fieldsClassName="batch-filter-fields">
        <Field label="Dịch vụ"><select value={serviceId} onChange={event=>{setServiceId(event.target.value);setPage(0)}}><option value="">Tất cả dịch vụ</option>{filterOptions.data?.services.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></Field>
        <Field label="Người tạo"><select value={createdBy} onChange={event=>{setCreatedBy(event.target.value);setPage(0)}}><option value="">Tất cả nhân viên</option>{filterOptions.data?.creators.map(option=><option key={option.id} value={option.id}>{option.label}</option>)}</select></Field>
        <Field label="Loại tải"><select value={loadType} onChange={event=>{setLoadType(event.target.value);setPage(0)}}><option value="">Tất cả loại tải</option><option value="PRIVATE">Giặt riêng</option><option value="SHARED">Ghép chung</option></select></Field>
        <Field label="Cần kiểm tra"><select value={warning} onChange={event=>{setWarning(event.target.value);setPage(0)}}><option value="">Tất cả</option><option value="ITEM_NOTE_PRESENT">Có ghi chú xử lý</option><option value="DIFFERENT_ITEM_TYPES">Trộn loại đồ</option><option value="PRIORITY_ITEM">Có món ưu tiên</option><option value="PROMISED_TIME_SOON">Hẹn trả trong 24 giờ</option></select></Field>
        <Field label="Từ ngày tạo"><input type="date" value={from} onChange={event=>{setFrom(event.target.value);setPage(0)}}/></Field>
        <Field label="Đến ngày tạo"><input type="date" min={from||undefined} value={to} onChange={event=>{setTo(event.target.value);setPage(0)}}/></Field>
        {activeFilterCount>0&&<Button type="button" variant="ghost" onClick={clearFilters}>Xóa lọc</Button>}
      </CollapsibleFilterPanel>
      <BatchList query={batches} page={page} onPage={setPage} hasActiveFilters={Boolean(search||activeFilterCount)}/></Surface>
  </div>
}

function BatchFlags({privateLoad,warnings}:{privateLoad:boolean;warnings:string[]}){return <span className="batch-list-flags">{privateLoad&&<span>Giặt riêng</span>}{warnings.map(code=><span key={code}>{warningText[code]??code}</span>)}</span>}

function BatchList({query,page,onPage,hasActiveFilters}:{query:ReturnType<typeof useQuery<Awaited<ReturnType<typeof washBatchApi.list>>>>;page:number;onPage:(page:number)=>void;hasActiveFilters:boolean}){
  if(query.isLoading)return <LoadingState rows={5}/>;if(query.isError)return <ErrorState title="Không tải được danh sách mẻ" body="Kiểm tra kết nối rồi thử lại." onRetry={()=>void query.refetch()}/>;if(!query.data?.items.length)return <StatePanel className="batch-empty-state" icon={<img className="batch-empty-illustration" src="/images/wash-batches/wash-batches-empty.png" alt=""/>} title={hasActiveFilters?'Không tìm thấy mẻ phù hợp':'Chưa có mẻ ở trạng thái này'} body={hasActiveFilters?'Thử đổi từ khóa hoặc bộ lọc nâng cao.':'Các mẻ phù hợp sẽ xuất hiện tại đây.'}/>
  return <><div className="batch-list-table"><table aria-label="Danh sách mẻ giặt"><thead><tr><th scope="col">Mã mẻ</th><th scope="col">Dịch vụ</th><th scope="col">Số đơn</th><th scope="col">Số món</th><th scope="col">Khối lượng / số lượng</th><th scope="col">Tạo lúc</th><th scope="col">Người tạo</th><th scope="col">Trạng thái</th><th scope="col">Thao tác</th></tr></thead><tbody>{query.data.items.map(item=><tr key={item.id}><td><Link to={`/wash-batches/${item.id}`}>{item.batchCode}</Link></td><td><span className="batch-list-service"><strong>{item.serviceName}</strong><BatchFlags privateLoad={item.privateLoad} warnings={item.warnings}/></span></td><td>{item.orderCount}</td><td>{item.itemCount}</td><td>{quantitiesText(item.quantities)}</td><td>{when(item.createdAt)}</td><td>{item.createdBy.displayName}</td><td><BatchStatusChip status={item.status}/></td><td><ButtonLink className="batch-list-table__view-button" size="sm" variant="ghost" to={`/wash-batches/${item.id}`}>Xem</ButtonLink></td></tr>)}</tbody></table></div><div className="batch-list-mobile">{query.data.items.map(item=><Link className="batch-list-card" to={`/wash-batches/${item.id}`} key={item.id}><span><strong>{item.batchCode}</strong><BatchStatusChip status={item.status}/></span><b>{item.serviceName}</b><BatchFlags privateLoad={item.privateLoad} warnings={item.warnings}/><p>{item.orderCount} đơn · {item.itemCount} món</p><strong>{quantitiesText(item.quantities)}</strong><small>Tạo {when(item.createdAt)} · {item.createdBy.displayName}</small></Link>)}</div>{query.data.totalPages>1&&<nav className="batch-pagination" aria-label="Phân trang mẻ giặt"><Button variant="secondary" size="sm" disabled={page===0} onClick={()=>onPage(Math.max(0,page-1))}><ChevronLeft size={17}/>Trước</Button><span>Trang {page+1} / {query.data.totalPages}</span><Button variant="secondary" size="sm" disabled={page+1>=query.data.totalPages} onClick={()=>onPage(page+1)}>Sau<ChevronRight size={17}/></Button></nav>}</>
}


export function WashBatchDetailPage(){
  const id=Number(useParams().batchId);const {branchId,hasPermission}=useAuth();const queryClient=useQueryClient();const {subscribe}=useRealtime();const {notify}=useToast()
  const detail=useQuery({queryKey:batchKeys.detail(id),queryFn:()=>washBatchApi.get(id,branchId!),enabled:Boolean(id&&branchId)});const canAudit=hasPermission(PERMISSION_CODES.BATCH_AUDIT_READ)
  const history=useQuery({queryKey:batchKeys.history(id),queryFn:()=>washBatchApi.history(id,branchId!),enabled:Boolean(id&&branchId&&canAudit)})
  const [addOpen,setAddOpen]=useState(false);const [readyOpen,setReadyOpen]=useState(false);const [cancelOpen,setCancelOpen]=useState(false);const [cancelReason,setCancelReason]=useState('');const [note,setNote]=useState('');const [addIds,setAddIds]=useState<number[]>([]);const [stale,setStale]=useState(false)
  useEffect(()=>{if(detail.data)setNote(detail.data.note??'')},[detail.data]);const editing=addOpen||note!==(detail.data?.note??'')
  useEffect(()=>subscribe('batch.',event=>{if(event.entityId!==id)return;if(editing)setStale(true);else{void queryClient.invalidateQueries({queryKey:batchKeys.detail(id)});void queryClient.invalidateQueries({queryKey:batchKeys.history(id)})}void queryClient.invalidateQueries({queryKey:['wash-batches','candidates']})}),[editing,id,queryClient,subscribe])
  const candidates=useQuery({queryKey:batchKeys.candidates(branchId,'',detail.data?.service.id),queryFn:()=>washBatchApi.candidates({branchId:branchId!,serviceId:detail.data!.service.id,page:0,size:100}),enabled:Boolean(addOpen&&branchId&&detail.data)})
  const command=useMutation({mutationFn:async(action:{type:'add'|'remove'|'note'|'ready'|'cancel';itemIds?:number[];reason?:string})=>{const batch=detail.data!;if(action.type==='add')return washBatchApi.addItems(id,branchId!,batch.version,action.itemIds!);if(action.type==='remove')return washBatchApi.removeItems(id,branchId!,batch.version,action.itemIds!);if(action.type==='note')return washBatchApi.updateNote(id,branchId!,batch.version,note.trim()||null);if(action.type==='ready')return washBatchApi.markReady(id,branchId!,batch.version);return washBatchApi.cancel(id,branchId!,batch.version,action.reason!)},onSuccess:value=>{queryClient.setQueryData(batchKeys.detail(id),value);void queryClient.invalidateQueries({queryKey:batchKeys.all});setAddOpen(false);setReadyOpen(false);setCancelOpen(false);setAddIds([]);setStale(false);notify({message:'Đã cập nhật mẻ giặt.',tone:'success'})},onError:error=>{if(error instanceof ApiError&&error.status===409)setStale(true);notify({message:apiMessage(error),tone:'error'})}})
  if(detail.isLoading)return <div className="page-container"><LoadingState/></div>;if(detail.isError||!detail.data)return <div className="page-container"><ErrorState title="Không tải được mẻ giặt" body="Mẻ không tồn tại hoặc nằm ngoài chi nhánh của bạn." onRetry={()=>void detail.refetch()}/></div>
  const batch=detail.data;const draft=batch.status==='DRAFT';const canUpdate=draft&&hasPermission(PERMISSION_CODES.BATCH_UPDATE);const selectedAdd=candidates.data?.items.filter(item=>addIds.includes(item.orderItemId))??[]
  return <div className="page-container wash-batch-detail"><header className="batch-detail-header"><div><Link className="back-link" to="/wash-batches"><ArrowLeft size={18}/>Mẻ giặt</Link><span><h1>{batch.batchCode}</h1><BatchStatusChip status={batch.status}/></span><p>{batch.service.name} · Tạo lúc {when(batch.createdAt)} · {batch.createdBy.displayName}</p></div><div className="batch-detail-actions">{canUpdate&&<Button variant="secondary" onClick={()=>setAddOpen(true)}>Thêm đồ</Button>}{draft&&hasPermission(PERMISSION_CODES.BATCH_MARK_READY)&&<Button variant="success" onClick={()=>setReadyOpen(true)}>Đánh dấu sẵn sàng</Button>}{['DRAFT','READY'].includes(batch.status)&&hasPermission(PERMISSION_CODES.BATCH_CANCEL)&&<Button variant="danger" onClick={()=>setCancelOpen(true)}>Hủy mẻ</Button>}</div></header>
    {stale&&<div className="stale-banner" role="alert"><AlertTriangle size={18}/><span>Mẻ giặt vừa được người khác cập nhật.</span><Button size="sm" variant="secondary" onClick={()=>{setStale(false);setAddIds([]);void detail.refetch()}}>Tải dữ liệu mới nhất</Button></div>}
    {batch.status==='READY'&&<div className="ready-helper"><CheckCircle2 size={19}/>Mẻ đã sẵn sàng để đưa vào máy.</div>}
    <div className="batch-detail-layout"><main><Surface className="batch-overview"><h2>Tổng quan</h2><dl><div><dt>Chi nhánh</dt><dd>{batch.branch.name}</dd></div><div><dt>Dịch vụ</dt><dd>{batch.service.name}</dd></div><div><dt>Số đơn</dt><dd>{batch.summary.orderCount}</dd></div><div><dt>Số món</dt><dd>{batch.summary.itemCount}</dd></div><div><dt>Tổng theo đơn vị</dt><dd>{quantitiesText(batch.summary.quantities)}</dd></div><div><dt>Trạng thái</dt><dd><BatchStatusChip status={batch.status}/></dd></div></dl></Surface>
      <Surface className="batch-items"><h2>Đồ trong mẻ</h2><BatchItemGroups items={batch.items} canRemove={canUpdate&&!stale&&batch.items.filter(item=>item.active).length>1} onRemove={(item:BatchItem)=>command.mutate({type:'remove',itemIds:[item.orderItemId]})}/>{canUpdate&&batch.items.filter(item=>item.active).length===1&&<p className="batch-final-item-help">Mẻ phải còn ít nhất 1 món. Hãy hủy mẻ nếu không còn sử dụng.</p>}</Surface></main>
      <aside><Surface className="batch-note"><h2>Ghi chú mẻ</h2>{canUpdate?<><textarea rows={5} maxLength={2000} value={note} onChange={event=>setNote(event.target.value)} disabled={stale}/><Button loading={command.isPending} disabled={stale||note===(batch.note??'')} onClick={()=>command.mutate({type:'note'})}>Lưu ghi chú</Button></>:<p>{batch.note||'Không có ghi chú.'}</p>}</Surface>
      {canAudit&&<BatchHistoryPanel query={history}/>}</aside></div>
    <OverlayDialog open={addOpen} onClose={()=>!command.isPending&&setAddOpen(false)} title="Thêm đồ vào mẻ" description={`Dịch vụ cố định: ${batch.service.name}`} variant="drawer" footer={<><Button variant="secondary" onClick={()=>setAddOpen(false)}>Đóng</Button><Button loading={command.isPending} disabled={!addIds.length||stale} onClick={()=>command.mutate({type:'add',itemIds:addIds})}>Thêm {addIds.length} món</Button></>}>
      {candidates.isLoading?<LoadingState rows={5}/>:candidates.isError?<ErrorState title="Không tải được đồ chờ ghép" body="Thử tải lại." onRetry={()=>void candidates.refetch()}/>:<div className="batch-candidate-grid">{candidates.data?.items.map(candidate=><BatchCandidateCard key={candidate.orderItemId} candidate={candidate} selected={addIds.includes(candidate.orderItemId)} compatibility={candidateCompatibility(candidate,[...batch.items.filter(item=>item.active),...selectedAdd.filter(item=>item.orderItemId!==candidate.orderItemId)])} onChange={checked=>setAddIds(current=>checked?[...current,candidate.orderItemId]:current.filter(value=>value!==candidate.orderItemId))}/>)}</div>}</OverlayDialog>
    <ConfirmDialog open={readyOpen} onClose={()=>setReadyOpen(false)} onConfirm={()=>command.mutate({type:'ready'})} pending={command.isPending} title="Xác nhận mẻ sẵn sàng" body={batch.warnings.length?`Có ${batch.warnings.length} mục cần kiểm tra trước khi sẵn sàng.`:'Thành phần mẻ sẽ được khóa để chờ đưa vào máy.'} confirmLabel="Xác nhận mẻ sẵn sàng"><ul className="warning-list">{batch.warnings.map(code=><li key={code}>{warningText[code]??code}</li>)}</ul></ConfirmDialog>
    <OverlayDialog open={cancelOpen} onClose={()=>setCancelOpen(false)} title={`Hủy mẻ ${batch.batchCode}`} description="Đồ trong mẻ sẽ quay lại danh sách chờ ghép." footer={<><Button variant="secondary" onClick={()=>setCancelOpen(false)}>Đóng</Button><Button variant="danger" loading={command.isPending} disabled={!cancelReason.trim()} onClick={()=>command.mutate({type:'cancel',reason:cancelReason.trim()})}>Xác nhận hủy</Button></>}><Field label="Lý do" required><textarea rows={4} maxLength={500} value={cancelReason} onChange={event=>setCancelReason(event.target.value)} autoFocus/></Field></OverlayDialog>
  </div>
}

function BatchHistoryPanel({query}:{query:ReturnType<typeof useQuery<BatchHistory[]>>}){return <Surface className="batch-history"><h2>Lịch sử mẻ</h2>{query.isLoading?<LoadingState rows={3}/>:query.isError?<ErrorState title="Không tải được lịch sử" body="Thử tải lại." onRetry={()=>void query.refetch()}/>:query.data?.map(item=><article key={item.id}><Clock3 size={15}/><div><strong>{historyText[item.action]??'Cập nhật mẻ'}</strong><p>{item.actor.displayName} · {when(item.createdAt)}</p>{item.reason&&<small>{item.reason}</small>}</div></article>)}</Surface>}
