import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, ArrowLeft, CheckCircle2, Clock3, Plus, Search } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { Link, useBeforeUnload, useBlocker, useNavigate, useParams, useSearchParams } from 'react-router-dom'
import { ApiError } from '../../api/client'
import { useAuth } from '../../auth/AuthProvider'
import { PERMISSION_CODES } from '../../auth/permissionCodes.generated'
import { ConfirmDialog, OverlayDialog } from '../../components/OverlayDialog'
import { ErrorState, LoadingState, StatePanel } from '../../components/States'
import { Field } from '../../components/Field'
import { Button, ButtonLink } from '../../components/ui/Button'
import { StatCard } from '../../components/ui/StatCard'
import { Surface } from '../../components/ui/Surface'
import { useRealtime } from '../../realtime/context'
import { useToast } from '../../providers/ToastProvider'
import { batchKeys, washBatchApi } from './api'
import { BatchCandidateCard, BatchItemGroups, BatchStatusChip, BatchSummary } from './BatchComponents'
import { candidateCompatibility, quantitiesText, quantityText, sharingText, warningText } from './presentation'
import type { BatchCandidate, BatchHistory, BatchItem } from './types'

const when=(value:string)=>new Date(value).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})
const historyText:Record<string,string>={CREATED:'Tạo mẻ',ITEMS_ADDED:'Thêm đồ vào mẻ',ITEMS_REMOVED:'Xóa đồ khỏi mẻ',NOTE_UPDATED:'Cập nhật ghi chú mẻ',MARKED_READY:'Đánh dấu sẵn sàng',CANCELLED:'Hủy mẻ'}
function apiMessage(error:unknown){if(!(error instanceof ApiError))return 'Không thể hoàn tất thao tác.';return ({BATCH_VERSION_CONFLICT:'Mẻ giặt vừa được người khác cập nhật.',BATCH_ITEM_ALREADY_ASSIGNED:'Một món vừa được xếp vào mẻ khác.',BATCH_INCOMPATIBLE:'Không thể ghép các món đã chọn.',BATCH_IMMUTABLE:'Mẻ đã sẵn sàng nên không thể thay đổi thành phần.'} as Record<string,string>)[error.problem.errorCode??'']??error.message}

type MainTab='candidates'|'DRAFT'|'READY'|'CANCELLED'
export function WashBatchListPage(){
  const {branchId,hasPermission}=useAuth();const navigate=useNavigate();const queryClient=useQueryClient();const {subscribe}=useRealtime()
  const [tab,setTab]=useState<MainTab>('candidates');const [search,setSearch]=useState('');const [serviceFilter,setServiceFilter]=useState('');const [sharingFilter,setSharingFilter]=useState('');const [dueFilter,setDueFilter]=useState('')
  const stats=useQuery({queryKey:batchKeys.stats(branchId),queryFn:()=>washBatchApi.stats(branchId!),enabled:Boolean(branchId)})
  const candidates=useQuery({queryKey:batchKeys.candidates(branchId,search),queryFn:()=>washBatchApi.candidates({branchId:branchId!,search,page:0,size:100}),enabled:Boolean(branchId)&&tab==='candidates'})
  const batches=useQuery({queryKey:batchKeys.list(branchId,tab==='candidates'?undefined:tab,search),queryFn:()=>washBatchApi.list({branchId:branchId!,status:tab==='candidates'?undefined:tab,search,page:0,size:50}),enabled:Boolean(branchId)&&tab!=='candidates'})
  useEffect(()=>subscribe('batch.',()=>{void queryClient.invalidateQueries({queryKey:batchKeys.all})}),[queryClient,subscribe])
  const serviceOptions=useMemo(()=>[...new Map((candidates.data?.items??[]).map(item=>[item.serviceId,item.serviceName])).entries()],[candidates.data])
  const filteredCandidates=useMemo(()=>{const soon=Date.now()+24*60*60*1000;return (candidates.data?.items??[]).filter(item=>(!serviceFilter||String(item.serviceId)===serviceFilter)&&(!sharingFilter||item.sharingMode===sharingFilter)&&(!dueFilter||(dueFilter==='SOON'&&Boolean(item.promisedAt)&&new Date(item.promisedAt!).getTime()<=soon)||(dueFilter==='NONE'&&!item.promisedAt)))},[candidates.data,dueFilter,serviceFilter,sharingFilter])
  const canCreate=hasPermission(PERMISSION_CODES.BATCH_CREATE)
  return <div className="page-container wash-batch-page"><header className="page-header"><div><p className="page-kicker">Điều phối xử lý</p><h1>Mẻ giặt</h1><p>Ghép đồ đang chờ thành các mẻ xử lý phù hợp.</p></div>{canCreate&&<ButtonLink to="/wash-batches/new" variant="create"><Plus size={18}/>Tạo mẻ</ButtonLink>}</header>
    <div className="batch-stats"><StatCard label="Đồ chờ ghép" value={stats.data?.candidateCount??'—'} tone="operational"/><StatCard label="Mẻ nháp" value={stats.data?.draftCount??'—'} tone="neutral"/><StatCard label="Mẻ sẵn sàng" value={stats.data?.readyCount??'—'} tone="success"/></div>
    <div className="batch-tabs" role="tablist" aria-label="Trạng thái mẻ">{([['candidates','Đồ chờ ghép'],['DRAFT','Mẻ nháp'],['READY','Sẵn sàng'],['CANCELLED','Đã hủy']] as const).map(([value,label])=><button key={value} role="tab" aria-selected={tab===value} onClick={()=>setTab(value)}>{label}</button>)}</div>
    <Surface className="batch-board"><label className="batch-search"><Search size={19}/><span className="sr-only">Tìm kiếm</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={tab==='candidates'?'Mã đơn, tên khách, số điện thoại':'Tìm theo mã mẻ'}/></label>
      {tab==='candidates'&&<details className="batch-filters" open><summary>Bộ lọc nâng cao</summary><div><label>Dịch vụ<select aria-label="Lọc theo dịch vụ" value={serviceFilter} onChange={event=>setServiceFilter(event.target.value)}><option value="">Tất cả dịch vụ</option>{serviceOptions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>Hình thức xử lý<select aria-label="Lọc theo hình thức xử lý" value={sharingFilter} onChange={event=>setSharingFilter(event.target.value)}><option value="">Tất cả hình thức</option><option value="SHARED_STANDARD">Giặt chung</option><option value="SHARED_PRIORITY">Ưu tiên ghép</option><option value="PRIVATE_LOAD">Giặt riêng</option></select></label><label>Hạn trả<select aria-label="Lọc theo hạn trả" value={dueFilter} onChange={event=>setDueFilter(event.target.value)}><option value="">Tất cả hạn trả</option><option value="SOON">Trong 24 giờ</option><option value="NONE">Chưa hẹn</option></select></label></div></details>}
      {tab==='candidates'?<CandidateQueue query={candidates} items={filteredCandidates} onPick={item=>navigate(`/wash-batches/new?item=${item.orderItemId}`)}/>:<BatchList query={batches}/>}</Surface>
  </div>
}

function CandidateQueue({query,items,onPick}:{query:ReturnType<typeof useQuery<Awaited<ReturnType<typeof washBatchApi.candidates>>>>;items:BatchCandidate[];onPick:(item:BatchCandidate)=>void}){
  if(query.isLoading)return <LoadingState rows={6}/>;if(query.isError)return <ErrorState title="Không tải được danh sách chờ" body="Kiểm tra kết nối rồi thử lại." onRetry={()=>void query.refetch()}/>;if(!items.length)return <StatePanel title="Không có đồ đang chờ ghép" body="Thử thay đổi bộ lọc hoặc tạo đơn mới ở trạng thái Đã nhận."/>
  return <><div className="batch-candidate-table"><table><thead><tr><th aria-label="Chọn"></th><th>Đơn</th><th>Khách hàng</th><th>Dịch vụ / Loại đồ</th><th>SL / KL</th><th>Hình thức</th><th>Hẹn trả</th><th>Trạng thái</th></tr></thead><tbody>{items.map(item=><tr key={item.orderItemId}><td><input type="checkbox" aria-label={`Chọn ${item.orderCode}`} onChange={()=>onPick(item)}/></td><td><strong>{item.orderCode}</strong></td><td>{item.customerName}<small>{item.customerPhone}</small></td><td>{item.serviceName}<small>{item.itemTypeName}</small></td><td>{quantityText(item.quantity,item.unitType)}</td><td>{sharingText(item.sharingMode)}</td><td>{item.promisedAt?when(item.promisedAt):'Chưa hẹn'}</td><td><span className="queue-status">Chờ ghép</span></td></tr>)}</tbody></table></div><div className="batch-candidate-mobile">{items.map(item=><BatchCandidateCard key={item.orderItemId} candidate={item} selected={false} onChange={()=>onPick(item)} compatibility={candidateCompatibility(item,[])}/>)}</div></>
}

function BatchList({query}:{query:ReturnType<typeof useQuery<Awaited<ReturnType<typeof washBatchApi.list>>>>}){
  if(query.isLoading)return <LoadingState rows={5}/>;if(query.isError)return <ErrorState title="Không tải được danh sách mẻ" body="Kiểm tra kết nối rồi thử lại." onRetry={()=>void query.refetch()}/>;if(!query.data?.items.length)return <StatePanel title="Chưa có mẻ ở trạng thái này" body="Các mẻ phù hợp sẽ xuất hiện tại đây."/>
  return <><div className="batch-list-table"><table><thead><tr><th>Mã mẻ</th><th>Dịch vụ</th><th>Số đơn</th><th>Số món</th><th>Khối lượng / số lượng</th><th>Tạo lúc</th><th>Người tạo</th><th>Trạng thái</th></tr></thead><tbody>{query.data.items.map(item=><tr key={item.id}><td><Link to={`/wash-batches/${item.id}`}>{item.batchCode}</Link></td><td>{item.serviceName}</td><td>{item.orderCount}</td><td>{item.itemCount}</td><td>{quantitiesText(item.quantities)}</td><td>{when(item.createdAt)}</td><td>{item.createdBy.displayName}</td><td><BatchStatusChip status={item.status}/></td></tr>)}</tbody></table></div><div className="batch-list-mobile">{query.data.items.map(item=><Link className="batch-list-card" to={`/wash-batches/${item.id}`} key={item.id}><span><strong>{item.batchCode}</strong><BatchStatusChip status={item.status}/></span><b>{item.serviceName}</b><p>{item.orderCount} đơn · {item.itemCount} món</p><strong>{quantitiesText(item.quantities)}</strong><small>Tạo {when(item.createdAt)} · {item.createdBy.displayName}</small></Link>)}</div></>
}

export function WashBatchCreatePage(){
  const {branchId,hasPermission}=useAuth();const navigate=useNavigate();const [params]=useSearchParams();const queryClient=useQueryClient();const {notify}=useToast();const [search,setSearch]=useState('');const [selectedIds,setSelectedIds]=useState<number[]>([]);const [note,setNote]=useState('');const allowLeave=useRef(false)
  const query=useQuery({queryKey:batchKeys.candidates(branchId,search),queryFn:()=>washBatchApi.candidates({branchId:branchId!,search,page:0,size:100}),enabled:Boolean(branchId)})
  useEffect(()=>{const id=Number(params.get('item'));if(id&&query.data?.items.some(item=>item.orderItemId===id))setSelectedIds(current=>current.includes(id)?current:[...current,id])},[params,query.data])
  const selected=useMemo(()=>query.data?.items.filter(item=>selectedIds.includes(item.orderItemId))??[],[query.data,selectedIds]);const dirty=selectedIds.length>0||Boolean(note)
  useBeforeUnload(event=>{if(dirty&&!allowLeave.current)event.preventDefault()});const blocker=useBlocker(()=>dirty&&!allowLeave.current)
  const create=useMutation({mutationFn:(markReady:boolean)=>washBatchApi.create({branchId:branchId!,orderItemIds:selectedIds,note:note.trim()||null,markReady}),onSuccess:value=>{allowLeave.current=true;void queryClient.invalidateQueries({queryKey:batchKeys.all});notify({message:value.status==='READY'?'Đã tạo và đánh dấu mẻ sẵn sàng.':'Đã lưu mẻ nháp.',tone:'success'});navigate(`/wash-batches/${value.id}`)},onError:error=>notify({message:apiMessage(error),tone:'error'})})
  const toggle=(candidate:BatchCandidate,checked:boolean)=>setSelectedIds(current=>checked?[...current,candidate.orderItemId]:current.filter(id=>id!==candidate.orderItemId))
  return <div className="page-container wash-batch-create"><header className="page-header"><div><Link className="back-link" to="/wash-batches"><ArrowLeft size={18}/>Mẻ giặt</Link><h1>Tạo mẻ giặt</h1><p>Chọn đồ có thể xử lý chung. Hệ thống sẽ kiểm tra các điều kiện đã biết trước khi tạo mẻ.</p></div></header>
    <div className="batch-create-layout"><Surface className="batch-selector"><label className="batch-search"><Search size={19}/><span className="sr-only">Tìm đồ chờ ghép</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Mã đơn, tên khách, số điện thoại"/></label>
      {query.isLoading?<LoadingState rows={6}/>:query.isError?<ErrorState title="Không tải được đồ chờ ghép" body="Thử tải lại danh sách." onRetry={()=>void query.refetch()}/>:!query.data?.items.length?<StatePanel title="Không có đồ đang chờ ghép" body="Đơn mới ở trạng thái Đã nhận sẽ xuất hiện tại đây."/>:<div className="batch-candidate-grid">{query.data.items.map(candidate=>{const compatibility=candidateCompatibility(candidate,selected.filter(item=>item.orderItemId!==candidate.orderItemId));return <BatchCandidateCard key={candidate.orderItemId} candidate={candidate} selected={selectedIds.includes(candidate.orderItemId)} compatibility={compatibility} onChange={checked=>toggle(candidate,checked)}/>})}</div>}</Surface>
      <Surface className="batch-create-summary"><h2>Mẻ đang tạo</h2><BatchSummary selected={selected}/><Field label="Ghi chú mẻ"><textarea rows={4} maxLength={2000} value={note} onChange={event=>setNote(event.target.value)} placeholder="Thông tin chung cho mẻ này"/></Field><div className="batch-summary-actions"><Button variant="secondary" loading={create.isPending} disabled={!selected.length} onClick={()=>create.mutate(false)}>Lưu mẻ nháp</Button><Button variant="success" loading={create.isPending} disabled={!selected.length||!hasPermission(PERMISSION_CODES.BATCH_MARK_READY)} onClick={()=>create.mutate(true)}>Đánh dấu sẵn sàng</Button></div></Surface></div>
    <div className="batch-mobile-action"><span><strong>{selected.length} món</strong><small>{new Set(selected.map(item=>item.orderId)).size} đơn</small></span><Button loading={create.isPending} disabled={!selected.length} onClick={()=>create.mutate(false)}>Tạo mẻ</Button></div>
    <ConfirmDialog open={blocker.state==='blocked'} onClose={()=>blocker.reset?.()} onConfirm={()=>blocker.proceed?.()} title="Bạn có thay đổi chưa lưu" body="Các món đang chọn sẽ bị bỏ nếu rời khỏi trang." confirmLabel="Rời khỏi trang" tone="danger"/>
  </div>
}

export function WashBatchDetailPage(){
  const id=Number(useParams().batchId);const {branchId,hasPermission}=useAuth();const queryClient=useQueryClient();const {subscribe}=useRealtime();const {notify}=useToast()
  const detail=useQuery({queryKey:batchKeys.detail(id),queryFn:()=>washBatchApi.get(id,branchId!),enabled:Boolean(id&&branchId)});const canAudit=hasPermission(PERMISSION_CODES.BATCH_AUDIT_READ)
  const history=useQuery({queryKey:batchKeys.history(id),queryFn:()=>washBatchApi.history(id,branchId!),enabled:Boolean(id&&branchId&&canAudit)})
  const [addOpen,setAddOpen]=useState(false);const [readyOpen,setReadyOpen]=useState(false);const [cancelOpen,setCancelOpen]=useState(false);const [cancelReason,setCancelReason]=useState('');const [note,setNote]=useState('');const [addIds,setAddIds]=useState<number[]>([]);const [stale,setStale]=useState(false)
  useEffect(()=>{if(detail.data)setNote(detail.data.note??'')},[detail.data]);const editing=addOpen||note!==(detail.data?.note??'')
  useEffect(()=>subscribe('batch.',event=>{if(event.entityId!==id)return;if(editing)setStale(true);else{void queryClient.invalidateQueries({queryKey:batchKeys.detail(id)});void queryClient.invalidateQueries({queryKey:batchKeys.history(id)})}void queryClient.invalidateQueries({queryKey:['wash-batches','candidates']})}),[editing,id,queryClient,subscribe])
  const candidates=useQuery({queryKey:batchKeys.candidates(branchId,'',detail.data?.service.id),queryFn:()=>washBatchApi.candidates({branchId:branchId!,serviceId:detail.data!.service.id,page:0,size:100}),enabled:Boolean(addOpen&&branchId&&detail.data)})
  const command=useMutation({mutationFn:async(action:{type:'add'|'remove'|'note'|'ready'|'cancel';itemIds?:number[];reason?:string})=>{const batch=detail.data!;if(action.type==='add')return washBatchApi.addItems(id,branchId!,batch.version,action.itemIds!);if(action.type==='remove')return washBatchApi.removeItems(id,branchId!,batch.version,action.itemIds!);if(action.type==='note')return washBatchApi.updateNote(id,branchId!,batch.version,note.trim()||null);if(action.type==='ready')return washBatchApi.markReady(id,branchId!,batch.version);return washBatchApi.cancel(id,branchId!,batch.version,action.reason!)},onSuccess:value=>{queryClient.setQueryData(batchKeys.detail(id),value);void queryClient.invalidateQueries({queryKey:batchKeys.all});setAddOpen(false);setReadyOpen(false);setCancelOpen(false);setAddIds([]);setStale(false);notify({message:'Đã cập nhật mẻ giặt.',tone:'success'})},onError:error=>{if(error instanceof ApiError&&error.status===409)setStale(true);notify({message:apiMessage(error),tone:'error'})}})
  if(detail.isLoading)return <div className="page-container"><LoadingState/></div>;if(detail.isError||!detail.data)return <div className="page-container"><ErrorState title="Không tải được mẻ giặt" body="Mẻ không tồn tại hoặc nằm ngoài chi nhánh của bạn." onRetry={()=>void detail.refetch()}/></div>
  const batch=detail.data;const draft=batch.status==='DRAFT';const canUpdate=draft&&hasPermission(PERMISSION_CODES.BATCH_UPDATE);const selectedAdd=candidates.data?.items.filter(item=>addIds.includes(item.orderItemId))??[]
  return <div className="page-container wash-batch-detail"><header className="batch-detail-header"><div><Link className="back-link" to="/wash-batches"><ArrowLeft size={18}/>Mẻ giặt</Link><span><h1>{batch.batchCode}</h1><BatchStatusChip status={batch.status}/></span><p>{batch.service.name} · Tạo lúc {when(batch.createdAt)} · {batch.createdBy.displayName}</p></div><div className="batch-detail-actions">{canUpdate&&<Button variant="secondary" onClick={()=>setAddOpen(true)}>Thêm đồ</Button>}{draft&&hasPermission(PERMISSION_CODES.BATCH_MARK_READY)&&<Button variant="success" onClick={()=>setReadyOpen(true)}>Đánh dấu sẵn sàng</Button>}{['DRAFT','READY'].includes(batch.status)&&hasPermission(PERMISSION_CODES.BATCH_CANCEL)&&<Button variant="danger" onClick={()=>setCancelOpen(true)}>Hủy mẻ</Button>}</div></header>
    {stale&&<div className="stale-banner" role="alert"><AlertTriangle size={18}/><span>Mẻ giặt vừa được người khác cập nhật.</span><Button size="sm" variant="secondary" onClick={()=>{setStale(false);setAddIds([]);void detail.refetch()}}>Tải dữ liệu mới nhất</Button></div>}
    {batch.status==='READY'&&<div className="ready-helper"><CheckCircle2 size={19}/>Mẻ đã sẵn sàng để đưa vào máy.</div>}
    <div className="batch-detail-layout"><main><Surface className="batch-overview"><h2>Tổng quan</h2><dl><div><dt>Chi nhánh</dt><dd>{batch.branch.name}</dd></div><div><dt>Dịch vụ</dt><dd>{batch.service.name}</dd></div><div><dt>Số đơn</dt><dd>{batch.summary.orderCount}</dd></div><div><dt>Số món</dt><dd>{batch.summary.itemCount}</dd></div><div><dt>Tổng theo đơn vị</dt><dd>{quantitiesText(batch.summary.quantities)}</dd></div><div><dt>Trạng thái</dt><dd><BatchStatusChip status={batch.status}/></dd></div></dl></Surface>
      <Surface className="batch-items"><h2>Đồ trong mẻ</h2><BatchItemGroups items={batch.items} canRemove={canUpdate&&!stale&&batch.items.filter(item=>item.active).length>1} onRemove={(item:BatchItem)=>command.mutate({type:'remove',itemIds:[item.orderItemId]})}/>{canUpdate&&batch.items.filter(item=>item.active).length===1&&<p className="batch-final-item-help">Mẻ phải còn ít nhất 1 món. Hãy hủy mẻ nếu không còn sử dụng.</p>}</Surface></main>
      <aside><Surface className="batch-note"><h2>Ghi chú mẻ</h2>{canUpdate?<><textarea rows={5} maxLength={2000} value={note} onChange={event=>setNote(event.target.value)} disabled={stale}/><Button loading={command.isPending} disabled={stale||note===(batch.note??'')} onClick={()=>command.mutate({type:'note'})}>Lưu ghi chú</Button></>:<p>{batch.note||'Không có ghi chú.'}</p>}</Surface>
      {canAudit&&<BatchHistoryPanel query={history}/>}</aside></div>
    <OverlayDialog open={addOpen} onClose={()=>!command.isPending&&setAddOpen(false)} title="Thêm đồ vào mẻ" description={`Dịch vụ cố định: ${batch.service.name}`} variant="drawer" footer={<><Button variant="secondary" onClick={()=>setAddOpen(false)}>Đóng</Button><Button loading={command.isPending} disabled={!addIds.length||stale} onClick={()=>command.mutate({type:'add',itemIds:addIds})}>Thêm {addIds.length} món</Button></>}>
      {candidates.isLoading?<LoadingState rows={5}/>:candidates.isError?<ErrorState title="Không tải được đồ chờ ghép" body="Thử tải lại." onRetry={()=>void candidates.refetch()}/>:<div className="batch-candidate-grid">{candidates.data?.items.map(candidate=><BatchCandidateCard key={candidate.orderItemId} candidate={candidate} selected={addIds.includes(candidate.orderItemId)} compatibility={candidateCompatibility(candidate,[...batch.items.filter(item=>item.active),...selectedAdd.filter(item=>item.orderItemId!==candidate.orderItemId)])} onChange={checked=>setAddIds(current=>checked?[...current,candidate.orderItemId]:current.filter(value=>value!==candidate.orderItemId))}/>)}</div>}</OverlayDialog>
    <ConfirmDialog open={readyOpen} onClose={()=>setReadyOpen(false)} onConfirm={()=>command.mutate({type:'ready'})} pending={command.isPending} title="Xác nhận mẻ sẵn sàng" body={batch.warnings.length?`Có ${batch.warnings.length} mục cần kiểm tra trước khi sẵn sàng.`:'Thành phần mẻ sẽ được khóa để chờ đưa vào máy.'} confirmLabel="Xác nhận mẻ sẵn sàng"><ul className="warning-list">{batch.warnings.map(code=><li key={code}>{warningText[code]??code}</li>)}</ul></ConfirmDialog>
    <OverlayDialog open={cancelOpen} onClose={()=>setCancelOpen(false)} title={`Hủy mẻ ${batch.batchCode}`} description="Đồ trong mẻ sẽ quay lại danh sách chờ ghép." footer={<><Button variant="secondary" onClick={()=>setCancelOpen(false)}>Đóng</Button><Button variant="danger" loading={command.isPending} disabled={!cancelReason.trim()} onClick={()=>command.mutate({type:'cancel',reason:cancelReason.trim()})}>Xác nhận hủy</Button></>}><Field label="Lý do" required><textarea rows={4} maxLength={500} value={cancelReason} onChange={event=>setCancelReason(event.target.value)} autoFocus/></Field></OverlayDialog>
  </div>
}

function BatchHistoryPanel({query}:{query:ReturnType<typeof useQuery<BatchHistory[]>>}){return <Surface className="batch-history"><h2>Lịch sử mẻ</h2>{query.isLoading?<LoadingState rows={3}/>:query.isError?<ErrorState title="Không tải được lịch sử" body="Thử tải lại." onRetry={()=>void query.refetch()}/>:query.data?.map(item=><article key={item.id}><Clock3 size={15}/><div><strong>{historyText[item.action]??'Cập nhật mẻ'}</strong><p>{item.actor.displayName} · {when(item.createdAt)}</p>{item.reason&&<small>{item.reason}</small>}</div></article>)}</Surface>}
