package com.laundry.management.servicecatalog.domain;

public enum PricingAuditAction {
    SERVICE_CREATED,
    SERVICE_UPDATED,
    SERVICE_STATUS_CHANGED,
    ITEM_TYPE_CREATED,
    ITEM_TYPE_UPDATED,
    ITEM_TYPE_MOVED,
    ITEM_TYPE_STATUS_CHANGED,
    PRICE_LIST_CREATED,
    PRICE_LIST_UPDATED,
    PRICE_LIST_DUPLICATED,
    PRICE_LIST_SCHEDULED,
    PRICE_LIST_PUBLISHED,
    PRICE_LIST_ARCHIVED,
    PRICE_RULE_CREATED,
    PRICE_RULE_UPDATED,
    PRICE_RULE_DELETED,
    PRICE_RULE_SUPERSEDED,
    PRICING_CONFLICT_OVERRIDDEN
}
