package com.laundry.management.servicecatalog.domain;

public enum PricingExplanationCode {
    STANDARD_UNIT_PRICE,
    MINIMUM_QUANTITY_APPLIED,
    MINIMUM_CHARGE_APPLIED,
    FIXED_PRICE,
    PER_LOAD_PRICE,
    HYBRID_INCLUDED_QUANTITY,
    HYBRID_EXCESS_QUANTITY,
    VOLUME_TIER_APPLIED,
    PROGRESSIVE_TIERS_APPLIED,
    BRANCH_OVERRIDE_APPLIED,
    GLOBAL_FALLBACK_APPLIED
}
