package com.laundry.management.notification.domain;

public enum NotificationType {
    EMPLOYEE_STATUS_CHANGED,
    EMPLOYEE_BRANCH_CHANGED,
    EMPLOYEE_ACCOUNT_LINKED,
    EMPLOYEE_ACCOUNT_LOCKED,
    ORDER_READY,
    ORDER_CANCELLED,
    ORDER_REOPENED,
    SYSTEM_ANNOUNCEMENT,
    GENERIC_INTERNAL
}
