ALTER TABLE branches CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_ai_ci;
ALTER TABLE users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_ai_ci;
ALTER TABLE roles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_ai_ci;
ALTER TABLE permissions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_ai_ci;
ALTER TABLE customers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_ai_ci;
ALTER TABLE customer_addresses CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_ai_ci;
ALTER TABLE customer_audit_activities CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_vi_0900_ai_ci;
