package com.laundry.management.employee.domain;

public enum EmployeeAuditAction {
    EMPLOYEE_CREATED,
    EMPLOYEE_UPDATED,
    EMPLOYEE_STATUS_CHANGED,
    EMPLOYEE_POSITION_CHANGED,
    EMPLOYEE_BRANCH_ASSIGNED,
    EMPLOYEE_BRANCH_REMOVED,
    EMPLOYEE_PRIMARY_BRANCH_CHANGED,
    EMPLOYEE_USER_LINKED,
    EMPLOYEE_USER_UNLINKED,
    LINKED_USER_LOCKED,
    COMPENSATION_VIEWED,
    COMPENSATION_HISTORY_VIEWED,
    COMPENSATION_UPDATED,
    IDENTITY_VIEWED,
    IDENTITY_UPDATED,
    IDENTITY_VERIFICATION_CHANGED,
    DOCUMENT_VIEWED,
    DOCUMENT_UPLOADED,
    DOCUMENT_REPLACED,
    DOCUMENT_DELETED,
    DOCUMENT_PREVIEWED,
    DOCUMENT_DOWNLOADED
}
