import { ArrowLeft, BriefcaseBusiness, Pencil, Plus, Save } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Link } from 'react-router-dom'
import { ApiError } from '../../api/client'
import { OverlayDialog } from '../../components/OverlayDialog'
import { ErrorState, LoadingState, PermissionDeniedState, StatePanel } from '../../components/States'
import { useToast } from '../../providers/ToastProvider'
import { useCreateEmployeePosition, useEmployeePositions, useUpdateEmployeePosition, type EmployeePositionInput } from './api'
import { PositionStatusBadge } from './EmployeeBadges'
import { employeePositionName } from './format'
import type { EmployeePosition } from './types'

const emptyPosition: EmployeePositionInput = { code: '', nameVi: '', nameEn: '', descriptionVi: '', descriptionEn: '', active: true, sortOrder: 0 }

export function EmployeePositionsPage() {
  const { t, i18n } = useTranslation()
  const query = useEmployeePositions(true)
  const [editing, setEditing] = useState<EmployeePosition | null | undefined>(undefined)
  return <div className="page-container employee-positions-page"><header className="page-header"><div className="employee-position-heading"><Link className="icon-button" to="/employees" aria-label={t('back')}><ArrowLeft size={20} /></Link><div><p className="eyebrow">{t('employee:title')}</p><h1>{t('employee:positionsTitle')}</h1><p>{t('employee:positionsSubtitle')}</p></div></div><div className="page-header__actions"><button className="button button--primary" onClick={() => setEditing(null)}><Plus size={18} />{t('employee:addPosition')}</button></div></header>{query.isPending ? <LoadingState rows={6} /> : query.error instanceof ApiError && query.error.status === 403 ? <PermissionDeniedState /> : query.isError ? <ErrorState title={t('employee:loadErrorTitle')} body={t('employee:loadErrorBody')} onRetry={() => void query.refetch()} /> : query.data?.length ? <div className="employee-position-list">{query.data.map((position) => <article key={position.id}><span className="employee-position-list__icon"><BriefcaseBusiness size={19} /></span><span><strong>{employeePositionName(position, i18n.language)}</strong><small>{position.code} · {i18n.language.startsWith('en') ? position.nameVi : position.nameEn}</small></span><PositionStatusBadge active={position.active} t={t} /><button className="icon-button" onClick={() => setEditing(position)} aria-label={t('employee:editPosition')} title={t('employee:editPosition')}><Pencil size={17} /></button></article>)}</div> : <StatePanel title={t('employee:positionsTitle')} body={t('employee:positionsSubtitle')} action={<button className="button button--primary" onClick={() => setEditing(null)}><Plus size={18} />{t('employee:addPosition')}</button>} />}<PositionDialog position={editing} onClose={() => setEditing(undefined)} /></div>
}

function PositionDialog({ position, onClose }: { position: EmployeePosition | null | undefined; onClose: () => void }) {
  const { t } = useTranslation(); const { notify } = useToast(); const [values, setValues] = useState<EmployeePositionInput>(emptyPosition); const createMutation = useCreateEmployeePosition(); const updateMutation = useUpdateEmployeePosition(position?.id ?? 0); const open = position !== undefined
  useEffect(() => { if (!open) return; setValues(position ? { code: position.code, nameVi: position.nameVi, nameEn: position.nameEn, descriptionVi: position.descriptionVi ?? '', descriptionEn: position.descriptionEn ?? '', active: position.active, sortOrder: position.sortOrder, version: position.version } : emptyPosition) }, [open, position])
  const set = (key: keyof EmployeePositionInput, value: string | number | boolean) => setValues((current) => ({ ...current, [key]: value }))
  const pending = createMutation.isPending || updateMutation.isPending
  const valid = Boolean(values.nameVi.trim() && values.nameEn.trim() && (position || values.code?.trim()))
  const submit = async () => { if (!valid) return; try { if (position) await updateMutation.mutateAsync({ ...values, active: values.active ?? true, version: position.version }); else await createMutation.mutateAsync({ ...values, code: values.code!.trim().toUpperCase() }); notify(t('employee:positionSaveSuccess')); onClose() } catch { notify(t('errors:genericBody'), 'error') } }
  return <OverlayDialog open={open} onClose={onClose} title={t(position ? 'employee:editPosition' : 'employee:addPosition')} footer={<><button className="button button--secondary" onClick={onClose}>{t('cancel')}</button><button className="button button--primary" onClick={() => void submit()} disabled={!valid || pending}><Save size={17} />{pending ? t('saving') : t('save')}</button></>}><div className="form-stack"><label className="field"><span>{t('employee:positionCode')}</span><input value={values.code ?? ''} readOnly={Boolean(position)} maxLength={60} onChange={(event) => set('code', event.target.value.toUpperCase())} /><small>{t('employee:positionCodeHint')}</small></label><label className="field"><span>{t('employee:positionNameVi')}</span><input value={values.nameVi} maxLength={150} onChange={(event) => set('nameVi', event.target.value)} /></label><label className="field"><span>{t('employee:positionNameEn')}</span><input value={values.nameEn} maxLength={150} onChange={(event) => set('nameEn', event.target.value)} /></label><label className="field"><span>{t('employee:descriptionVi')}</span><textarea rows={3} value={values.descriptionVi ?? ''} maxLength={500} onChange={(event) => set('descriptionVi', event.target.value)} /></label><label className="field"><span>{t('employee:descriptionEn')}</span><textarea rows={3} value={values.descriptionEn ?? ''} maxLength={500} onChange={(event) => set('descriptionEn', event.target.value)} /></label><label className="field"><span>{t('employee:sortOrder')}</span><input type="number" min={0} inputMode="numeric" value={values.sortOrder} onChange={(event) => set('sortOrder', Number(event.target.value))} /></label>{position && <label className="switch-row"><input type="checkbox" checked={values.active ?? true} onChange={(event) => set('active', event.target.checked)} /><span className="switch" aria-hidden="true" /><span>{values.active ? t('employee:positionActive') : t('employee:positionInactive')}</span></label>}</div></OverlayDialog>
}
